apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-multiarch
spec:
  params:
  - name: GIT_REPO
    type: string
  - default: main
    name: GIT_REVISION
    type: string
  - default: build-multiarch
    name: IMAGESTREAM_NAME
    type: string
  - default: latest
    name: IMAGESTREAM_TAG
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: ./Dockerfile
    name: DOCKERFILE
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build-amd64
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.IMAGESTREAM_NAME):$(params.IMAGESTREAM_TAG)-amd64
    - name: TLSVERIFY
      value: "true"
    - name: CONTEXT
      value: $(params.PATH_CONTEXT)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE)
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: build-arm64
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.IMAGESTREAM_NAME):$(params.IMAGESTREAM_TAG)-arm64
    - name: TLSVERIFY
      value: "true"
    - name: DOCKERFILE
      value: $(params.DOCKERFILE)
    - name: CONTEXT
      value: $(params.PATH_CONTEXT)
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: build-manifest-list
    runAfter:
    - build-amd64
    - build-arm64
    taskRef:
      kind: Task
      name: buildah-manifest
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.IMAGESTREAM_NAME):$(params.IMAGESTREAM_TAG)
    - name: IMAGE_AMD64
      value: $(tasks.build-amd64.results.IMAGE_URL)
    - name: IMAGE_ARM64
      value: $(tasks.build-arm64.results.IMAGE_URL)
  results:
  - description: Digest of the manifest list built.
    name: MANIFEST_DIGEST
    value: $(tasks.build-manifest-list.results.IMAGE_DIGEST)
  - description: Image repository where manifest list was pushed.
    name: MANIFEST_URL
    value: $(tasks.build-manifest-list.results.IMAGE_URL)
  - description: Commit SHA of the git revision that was cloned.
    name: GIT_COMMIT
    value: $(tasks.git-clone.results.commit)
  workspaces:
  - name: workspace
