apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sample-go-multiarch-
spec:
  params:
  - name: GIT_REPO
    value: https://github.com/adambkaplan/sample-go-multiarch
  - name: GIT_REVISION
    value: main
  - name: IMAGESTREAM_NAME
    value: sample-go-multiarch
  - name: IMAGESTREAM_TAG
    value: demo
  - name: DOCKERFILE
    value: ./Containerfile
  pipelineRef:
    name: build-multiarch
  taskRunSpecs:
  - pipelineTaskName: build-amd64
    podTemplate:
      nodeSelector:
        kubernetes.io/arch: amd64
  - pipelineTaskName: build-arm64
    podTemplate:
      nodeSelector:
        kubernetes.io/arch: arm64
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: build-multiarch
